#########################################
# Set up and common commands & packages #
#########################################

# Checks that relevant packages (**not** imports!) are available and if so loads them in the workspace
if (!isTRUE(requireNamespace("icons", quietly = TRUE))) {
  stop("You need to install the packages 'icons'. Please run in your R terminal:\n remotes::install_github('mitchelloharawild/icons')")
}
# If 'icons' is installed but not loaded then attach the Namespace (so that all the relevant functions are available)
if (isTRUE(requireNamespace("icons", quietly = TRUE))) {
  if (!is.element("icons", (.packages()))) {
    attachNamespace("icons")
  }
}

# Sets default fonts for tikz
library(tikzDevice)
options(tikzLatexPackages=c(getOption("tikzLatexPackages"),"\\usepackage{inconsolata,}",
                            "\\usepackage[scaled=.89]{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}\n"))

# Trick to automatically convert pdf graphs generated with dev='tikz' into png so they work in html format
# see: https://github.com/rstudio/bookdown/issues/275
# NB: Need to specify 'density=600' in 'image_read' to get same quality as tikz
knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x)
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x,density=600), x2, format = 'png', quality=90, density=600)
      x2
    }
  }
  options
})

# This is a hack to insert 'alt-text' in images created by the R chunks
# source: https://ropensci.org/technotes/2020/04/23/rmd-learnings/
# NB: the 'alt-text' needs to be **'title'** attribute that gets included in the list 'opts'
# which is included as part of the set up in the chunk, for example
#    ```{r echo=FALSE,opts=list(title="Alt-text",width="45%"...)}
# (see: https://www.computerhope.com/issues/ch001076.htm).
# Also, needs to specify the 'width' option (= what would normally be 'out.width') to ensure
# that the resulting HTML code to format the graph
knitr::knit_hooks$set(
  plot = function(x, options) {
    opts <- options$opts
    paste0(
      "<img src=",
      '"', x, '" ',
      if (!is.null(opts)) {
        # Here include the styling for the graphs - this ensure it's centered
        paste('style="display: block; margin: auto;"',
              # And this "glues" the options passed by the user (including the 'alt-text')
              glue::glue_collapse(glue::glue('{names(opts)}="{opts}"'),sep = " ")
        )
      },
      ">\n"
    )
  },
  # This sets up a switch that allows to automatically crop the images generated by R
  # https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html
  knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
)

# Defaults for figure size
# fig.retina=3 improves the quality of the resulting graph (https://arm.rbind.io/slides/xaringan.html#89)
knitr::opts_chunk$set(fig.width=10, fig.height=9, out.width="55%", fig.align='center', fig.retina=3, crop=TRUE,
                      comment=NA,message=FALSE,error=FALSE)



# This sets up the figure path so that all the R-generated images are stored under 'img'
knitr::opts_chunk$set(fig.path="./img/")


# Table/knitr-related options
library(knitr)
library(kableExtra)
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# This defines how the code is formatted
knitr::opts_chunk$set(
  prompt = TRUE,
  highlight = TRUE,
  #background = '#FFFFFF',
  concordance=TRUE
)


# Spacing - uses R to create HTML code to make space
vspace=function(space="-20px") {
  paste('<span style="display:block; margin-top:',space,';"></span>')
}
# This creates a 'tab' function that adds horizontal space(s) --- default is 1 but can add as many as you like
tab=function(x=1) {
  cat(rep("&nbsp;",3),sep="")
}


# LaTeX maths & colors:
# Defines a LaTeX macro to typeset text using the default font (as for the rest of the text in the slides)
sftext=function(x) {
  paste0("\\style{font-family:inherit;}{\\text{",x,"}}")
}
# can use xaringan colors for equations, eg '.red[$$x^2$$]'
# if a color is not named (but defined in the .css file), need to use the MathJax command '\class', eg '$\class{color}{x^2}$'


# Macro to include figures from file
# NB: It assumes by default that the images to be loaded are in the 'img' folder under the current directory
#     ie where the current Rmd presentation is stored. But a full directory can be passed on in the argument 'dir'
include_fig=function(img,dir="./img",width="100%",title="INCLUDE TEXT HERE") {
  filename=file.path(dir,img)
  paste0("<center><img src=",filename," width='",width,"' title='",title,"'></center>")
}

# Creates HTML code to include the samptux icon + link to gianluca.statistica.it
samptux=function(path="assets/logo.png",width="2.0%",text="") {
  paste0('<span><a href="https://gianluca.statistica.it/"><img src="',path,'" title="Go home" width="',width,'"></a>',text,'</span>')
  # But could use other links/icons, eg
  #<p><a href="https://gianluca.statistica.it/"><i class="fas fa-home" title="Go home" style="color: #bcc0c4;"></i></a></p>
  # Also, could use the 'xaringanExtra::use_logo()' function as well (which does pretty much the same thing...)
}

# Adds icons & links on the bottom navbar (in the dedicated 'footer-social' container)
add_twitter=function(url="https://twitter.com/giabaio",title="Follow me on Twitter",fill="#bcc0c4") {
  paste0('&nbsp;<a href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("twitter"),scale=.8,fill=fill,bottom="1em"),'</a>&nbsp;')
}
add_email=function(email="g.baio@ucl.ac.uk",title="Email me",fill="#bcc0c4") {
  paste0('&nbsp;<a href="mailto:',email,'"; title="',title,'">',icons::icon_style(icons::fontawesome("envelope",style = "solid"),scale=.8,fill=fill),'</a>&nbsp;')
}
add_website=function(url="https://gianluca.statistica.it",title="Visit my website",fill="#bcc0c4") {
  paste0('&nbsp;<a href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("firefox"),scale=.8,fill=fill),'</a>&nbsp;')
}
add_github=function(url="https://github.com/giabaio",title="Check out my repos",fill="#bcc0c4") {
  paste0('&nbsp;<a href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("github"),scale=.8,fill=fill),'</a>&nbsp;')
}
add_linkedin=function(url="https://www.linkedin.com/in/gianluca-baio-b893879/",title="Follow me on LinkedIn",fill="#2867b2") {
  paste0('&nbsp;<a href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("linkedin"),scale=.8,fill=fill,bottom="1em"),'</a>&nbsp;')
}
add_podcast=function(url="https://soundcloud.com/uclsound/sets/sample-space",title="Random Talks",fill="#FE5000") {
  paste0('&nbsp;<a href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("soundcloud"),scale=.8,fill=fill,bottom="1em"),'</a>&nbsp;')
}
course_site=function(url="https://egon.stats.ucl.ac.uk/static/stat0019/",title="Back to STAT0019 website",fill="#bcc0c4") {
  paste0('&nbsp;<a target="_self" href="',url,'"; title="',title,'">',icons::icon_style(icons::fontawesome("home"),scale=1,fill=fill,bottom="1em"),'</a>&nbsp;')
}
# Makes css/html code to create post-its with variable inputs
postit=function(text="This is some text",top="50%",left="2.5%",fontsize="85%",height="4em",width="4em",rotate="6deg") {
  paste0(
    '<p style="position: absolute; top:',top,'; left:',left,'; font-family: Nanum Pen Script; font-size:',fontsize,
    '; text-decoration: none; color: #000; background: #ffc; display: block; height:',height,'; width:',width,
    '; padding: .5em; box-shadow: 5px 5px 7px rgba(33,33,33,.7); transform: rotate(',rotate,'); border-bottom-right-radius: 60px 5px;">',text,'</p>'
  )
}

twitter=function(alt="") {
  icon="assets/images/twitter.png"
  link="https://twitter.com/gianlubaio"
  htmltools::tags$a(.noWS = c("after-begin", "before-end"),
                    href = link,
                    htmltools::tags$img(src = icon, alt = alt, width = "32", height = "32", style = "border: none;")
  )
}
linkedin=function(alt="") {
  icon="images/linkedin.png"
  link="https://www.linkedin.com/in/gianluca-baio-b893879/"
  htmltools::tags$a(.noWS = c("after-begin", "before-end"),
                    href = link,
                    htmltools::tags$img(src = icon, alt = alt, width = "32", height = "32", style = "border: none;")
  )
}
github=function(alt="") {
  icon="images/github.png"
  link="https://www.github.com/giabaio"
  htmltools::tags$a(.noWS = c("after-begin", "before-end"),
                    href = link,
                    htmltools::tags$img(src = icon, alt = alt, width = "32", height = "32", style = "border: none;")
  )
}
scholar=function(alt="") {
  icon="images/scholar.png"
  link="https://scholar.google.com/citations?user=ro0QvGsAAAAJ&hl=en"
  htmltools::tags$a(.noWS = c("after-begin", "before-end"),
                    href = link,
                    htmltools::tags$img(src = icon, alt = alt, width = "32", height = "32", style = "border: none;")
  )
}
researchgate=function(alt="") {
  icon="images/researchgate.png"
  link="https://www.researchgate.net/profile/Gianluca_Baio"
  htmltools::tags$a(.noWS = c("after-begin", "before-end"),
                    href = link,
                    htmltools::tags$img(src = icon, alt = alt, width = "32", height = "32", style = "border: none;")
  )
}

# Relevant packages (to load globally - not for a single slide)
library(dplyr)
library(ggplot2)
library(xaringanExtra)


# Citations & Bibliography (https://github.com/yihui/xaringan/wiki/Bibliography-and-citations)
# RefManageR: https://arxiv.org/pdf/1403.2036v1.pdf
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           style = "markdown",
           cite.style = "authoryear",
           super = FALSE,
           hyperlink = FALSE,
           dashed = FALSE
#           bibpunct = c("(",")","(",")",";",","),
)


# Formats the date in the title-slide
# If the date is specified as a string (to a specific value), then used that, else use current date
if(!is.null(rmarkdown::metadata$params$date)){date=rmarkdown::metadata$params$date} else {date=format(Sys.Date(),"%e %B %Y")}

# Also creates a variable 'short_date' that can be used in the footers
short_date=format(as.Date(date,format="%e %b %Y"),"%e %b %Y")

#### Extra stuff needed for the slides
# Books and cross-references
book_links=list(
  bmhe=list(
    library="https://ucl.rl.talis.com/link?url=http%3A%2F%2Flibproxy.ucl.ac.uk%2Flogin%3Fqurl%3Dhttps%253A%252F%252Fdoi.org%252F10.1201%252Fb13099&sig=3aebc20479b70f36a22609520951c13ac9cfd52cb8fbf0b8d1c46a857432d1a6",
    crc="https://www-taylorfrancis-com.libproxy.ucl.ac.uk/books/9780429111396",
    site="https://gianluca.statistica.it/bmhe",
    github="https://github.com/giabaio/BCEA"
  ),
  daniels=list(
    library="https://ucl-new-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=UCL_LMS_DS21127553340004761&context=L&vid=UCL_VU2&lang=en_US&search_scope=CSCOP_UCL&adaptor=Local%20Search%20Engine&tab=local&query=any,contains,%20Missing%20Data%20in%20Longitudinal%20Studies:&offset=0",
    crc="https://www.routledge.com/Missing-Data-in-Longitudinal-Studies-Strategies-for-Bayesian-Modeling-and/Daniels-Hogan/p/book/9781584886099"
  ),
  bugs_book=list(
    library="https://ebookcentral.proquest.com/lib/ucl/reader.action?docID=1501675",
    crc="https://www.routledge.com/The-BUGS-Book-A-Practical-Introduction-to-Bayesian-Analysis/Lunn-Jackson-Best-Thomas-Spiegelhalter/p/book/9781584888499"
  ),
  esdm=list(
    library="http://web.a.ebscohost.com.libproxy.ucl.ac.uk/ehost/detail/detail?vid=0&sid=a0d65028-2c2d-43da-ab5b-3dd7dc63cfd2%40sdc-v-sessmgr03&bdata=JkF1dGhUeXBlPWlwLHNoaWImc2l0ZT1laG9zdC1saXZlJnNjb3BlPXNpdGU%3d#AN=1689059&db=nlebk",
    wiley="https://www.wiley.com/en-gb/Evidence+Synthesis+for+Decision+Making+in+Healthcare-p-9780470061091"
  ),
  gelman_hill=list(
    library="https://ucl-new-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=UCL_LMS_DS21154188240004761&context=L&vid=UCL_VU2&lang=en_US&search_scope=CSCOP_UCL&adaptor=Local%20Search%20Engine&tab=local&query=any,contains,Data%20analysis%20using%20regression%20and%20multilevel&offset=0",
    cup="https://www.cambridge.org/core/books/data-analysis-using-regression-and-multilevelhierarchical-models/32A29531C7FD730C3A68951A17C9D983",
    site="http://www.stat.columbia.edu/~gelman/book/"
  ),
  bda=list(
    library="https://ucl-new-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=UCL_LMS_DS51251534660004761&context=L&vid=UCL_VU2&lang=en_US&search_scope=CSCOP_UCL&adaptor=Local%20Search%20Engine&isFrbr=true&tab=local&query=any,contains,bayesian%20data%20analysis&sortby=rank&facet=frbrgroupid,include,1391247635&offset=0",
    crc="https://www.routledge.com/Bayesian-Data-Analysis/Gelman-Carlin-Stern-Dunson-Vehtari-Rubin/p/book/9781439840955",
    site="http://www.stat.columbia.edu/~gelman/book/"
  ),
  kruschke=list(
    library="https://ucl-new-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=UCL_LMS_DS51243107000004761&context=L&vid=UCL_VU2&lang=en_US&search_scope=CSCOP_UCL&adaptor=Local%20Search%20Engine&tab=local&query=any,contains,doing%20bayesian%20data%20analysis&offset=0",
    site="https://sites.google.com/site/doingbayesiandataanalysis/"
  ),
  bacthc=list(
    library="https://ucl.rl.talis.com/link?url=https%3A%2F%2Fucl.userservices.exlibrisgroup.com%2Fview%2Faction%2Furesolver.do%3Foperation%3DresolveService%26package_service_id%3D6967508210004761%26institutionId%3D4761%26customerId%3D4760&sig=02aba6332c92e1bd50862e1688f21d4b9dca85ca028a0828a8f7bd31f00a88a2",
    wiley="https://onlinelibrary.wiley.com/doi/book/10.1002/0470092602"
  ),
  briggs=list(
    library="https://ucl-new-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=UCL_LMS_DS51260536580004761&context=L&vid=UCL_VU2&lang=en_US&search_scope=CSCOP_UCL&adaptor=Local%20Search%20Engine&tab=local&query=any,contains,Decision%20Modelling%20for%20Health%20Economic%20Evaluation&offset=0",
    oup="https://global.oup.com/academic/product/decision-modelling-for-health-economic-evaluation-9780198526629?cc=gb&lang=en&"
  ),
  nma_r=list(
    site="https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/",
    github="https://mathiasharrer.github.io/Doing-Meta-Analysis-in-R/"
  ),
  bcea=list(
    springer="http://www.springer.com/us/book/9783319557168",
    site="https://gianluca.statistica.it/book/bcea/"
  )
)

bmhe=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Bayesian Methods in Health Economics</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$bmhe$library,')] .button[<img src="../img/routledge.png" width="7%"> [Book website (CRC)](',book_links$bmhe$crc,')] .button[<i class="fab fa-firefox"></i> [Book website](',book_links$bmhe$site,')] .button[<i class="fab fa-github"></i> [Code](',book_links$bmhe$github,')]')
}

bugs_book=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>The BUGS Book</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$bugs_book$library,')] .button[<img src="../img/routledge.png" width="10%"> [Book website](',book_links$bugs_book$crc,')]')
}

daniels=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Missing data in longitudinal studies</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$daniels$library,')] .button[<img src="../img/routledge.png" width="10%"> [Book website](',book_links$daniels$crc,')]')
}

esdm=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Evidence Synthesis for Decision Making in Healthcare</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$esdm$library,')] .button[<img src="../img/wiley.png" width="10%"> [Book website](',book_links$esdm$wiley,')]')
}

gelman_hill=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Data Analysis Using Regression and Multilevel/Hierarchical Models</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$gelman_hill$library,')] .button[<img src="../img/cup.png" width="10%"> [Book website (CUP)](',book_links$gelman_hill$crc,')] .button[<i class="fab fa-firefox"></i> [Book website](',book_links$gelman_hill$site,')]')
}

kruschke=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Doing Bayesian Data Analysis</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$kruschke$library,')] .button[<i class="fab fa-firefox"></i> [Book website](',book_links$kruschke$site,')]')
}

bacthc=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Bayesian approaches to clinical trials and health care evaluation</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$bacthc$library,')] .button[<img src="../img/wiley.png" width="10%"> [Book website](',book_links$bacthc$wiley,')]')
}

briggs=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Decision Modelling for Health Economic Evaluation</i>',txt_chapter,
         ' .button[<img src="../img/ucl-icon.png" width="18%"> [Library](',book_links$briggs$library,')] .button[<img src="../img/oup-1.png" width="10%">  [Book website](',book_links$briggs$oup,')]')
}

nma_r=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Doing Meta-Analysis in R</i>',txt_chapter,
         ' .button[<i class="fab fa-firefox"></i>  [Book website](',book_links$nma_r$site,')] .button[<i class="fab fa-github"></i> [Code](',book_links$nma_r$github,')]')
}

bcea_book=function(chapter=NULL) {
  if(is.null(chapter)) {txt_chapter=" "} else {
    txt_chapter=ifelse(
      length(chapter)==1, paste0(", chapter ",chapter),
      paste0(", chapters ",paste0(chapter,collapse=", "))
    )
  }
  paste0(icon::fontawesome("book"),' <i>Bayesian Cost-Effectiveness Analysis with the R package BCEA</i>',txt_chapter,
         ' .button[<img src="../img/springer.png" width="8%"> [Book website (Springer)](',book_links$bcea$springer,')] .button[<i class="fab fa-firefox"></i> [Book website](',book_links$bcea$site,')]')
}


# Here creates a tibble with the full syllabus and name of each lecture, with the full path
syllabus=tibble(
  title=c(
    "intro_bayes",
    "bugs",
    "mcmc",
    "intro_he",
    "ild",
    "survival",
    "ald",
    "nma",
    "mm",
    "missing",
    "voi"
  ),
  number=c(
    1,2,3,4,5,6,7,8,9,10,11
  ),
  path=c(
    "01_Intro",
    "02_BUGS",
    "03_MCMC",
    "04_Intro_HE",
    "05_ILD",
    "06_Survival",
    "07_ALD",
    "08_NMA",
    "09_MM",
    "10_Missing",
    "11_VoI"
  )
)

#' Then this function formats the link-out to the lecture file
#' @param lecture The title of the lecture (as given in the table 'syllabus' in the column 'title')
#' @param name The name of a given slide (if given in the preamble to the slide, eg 'name: a-given-name')
ref_lecture=function(lecture,name=NULL) {
  if(!is.null(name)) {
    url=paste0("/#",name)
  } else {
    url="/index.html"
  }
  paste0('<a href="../',syllabus %>% filter(title==lecture) %>% pull(path),url,'">Lecture ',syllabus %>% filter(title==lecture) %>% pull(number),'</a>')
}

previous_slide=function(lecture) {
  paste0(icon::fontawesome("arrow-circle-left"),' <a href="../',syllabus %>% filter(title==lecture) %>% pull(path),'/index.html" style="color:#C5283D!important; font-family: Ubuntu;">Previous lecture</a>')
}

# Tries to define custom icons = academicons (should work automatically but for some reasons it doesn't...)
# https://github.com/mitchelloharawild/icon 
# NB Don't need this after update in icons...
#custom=icon::icon_set("../img/academicons")
