---
title: "Introduction to the Department of Statistical Science"
author: Gianluca Baio
date: ""
institute: "[Department of Statistical Science](https://www.ucl.ac.uk/statistics/) | University College London"
params: 
   conference: "Foundation Fortnight"
   location: "Department of Statistical Science, UCL"
   short_title: "Foundation Fortnight"
output:
  xaringan::moon_reader:
    includes: 
       in_header: "assets/latex_macros.html" 
       # This line adds a logo based on the format selected in the file 'assets/include_logo.html'
       # NB: the actual options (eg placement of the logo and actual logo file) can be changed there
       # after_body: "assets/insert-logo.html"
    seal: false
    yolo: no
    lib_dir: libs
    nature:
      beforeInit: ["https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: yes
      countIncrementalSlides: no
      ratio: '16:9'
      titleSlideClass:
      - center
      - middle
    self_contained: false 
    css:
    - "assets/ucl-powerpoint.css"
---

```{r echo=F,message=FALSE,warning=FALSE,comment=NA}
# Sources the R file with all the relevant setup and commands
source("assets/setup.R")

# Stuff from 'xaringanExtra' (https://pkg.garrickadenbuie.com/xaringanExtra)
# This allows the use of panels (from 'xaringanExtra')
xaringanExtra::use_panelset()
# This allows to copy code from the slides directly
xaringanExtra::use_clipboard()
# This freezes the frame for when there's a gif included
xaringanExtra::use_freezeframe()

# Defines the path to the file with the .bib entries (in case there are references)
bibfile=ReadBib("~/Dropbox/Perso/Office/CV/mypubs.bib",check = FALSE)
```

class: title-slide

# `r rmarkdown::metadata$title`    

## `r rmarkdown::metadata$author`    

### `r rmarkdown::metadata$institute`    

.title-small[
`r icon::icon_style(icon::fontawesome("envelope",style = "solid"),scale=.8,fill="#00acee")`  [g.baio@ucl.ac.uk](mailto:g.baio@ucl.ac.uk)
`r icon::icon_style(icon::fontawesome("firefox"),scale=.8,fill="#EA7600")`  [http://www.statistica.it/gianluca/](http://www.statistica.it/gianluca/)
`r icon::icon_style(icon::fontawesome("firefox"),scale=.8,fill="#EA7600")`  [https://egon.stats.ucl.ac.uk/research/statistics-health-economics/](https://egon.stats.ucl.ac.uk/research/statistics-health-economics/)
`r icon::icon_style(icon::fontawesome("github"),scale=.8,fill="black")`  [https://github.com/giabaio](https://github.com/giabaio)
`r icon::icon_style(icon::fontawesome("github"),scale=.8,fill="black")`  [https://github.com/StatisticsHealthEconomics](https://github.com/StatisticsHealthEconomics)
`r icon::icon_style(icon::fontawesome("twitter"),scale=.8,fill="#00acee")`  [@gianlubaio](https://twitter.com/gianlubaio)     
]

### `r rmarkdown::metadata$params$conference`    
`r rmarkdown::metadata$params$location` 

<!-- Can also separate the various components of the extra argument 'params', eg as in 
### `r paste(rmarkdown::metadata$params, collapse=", ")`
-->



<!-- This adds a footer (optional and with other possibilities...) -->
.footer-left[
`r samptux()` <span style="position: relative; bottom: 5px; color: #D5D5D5;"> &nbsp; &copy; Gianluca Baio (UCL)</span>
]

---

layout: true
.footer-left[
`r samptux()` <span style="position: relative; bottom: 5px; color: #D5D5D5;"> &nbsp; &copy; Gianluca Baio (UCL)</span>
]
<!-- Can also include social media icons & hyperlinks -->
.footer-social[
`r add_twitter()` `r add_email()` `r add_website()`
]

<!-- Can also add a center footer, eg to include the title of the talk -->
.footer-center[

]
<!-- And a right footer, to include the date -->
.footer-right[
`r rmarkdown::metadata$params$conference`
]

---

# Teaching this year: useful links

## Safety on campus:

- [General information](https://www.ucl.ac.uk/safety-services/working-safely-during-pandemic)

- [Information on Covid-19 and UCL](https://www.ucl.ac.uk/coronavirus/)
   
- [Keeping safe on campus](https://www.ucl.ac.uk/coronavirus/keeping-safe-campus)

`r vspace("30px")`

## Useful links
- [Instructions for Zoom installation and use](https://www.ucl.ac.uk/isd/services/communicate-collaborate/zoom) (require UCL user ID and password)

- As you know, [Moodle](https://moodle.ucl.ac.uk) is often your first port of call for anything teaching-related...

---

# Whom to contact with questions

## Questions about a module you’re studying: 

- **Course lecturer** in first instance

- Then, in order: 

   1. Your personal tutor 
   2. Jinghao ([jinghao.xue@ucl.ac.uk](mailto: jinghao.xue@ucl.ac.uk)) 
   3. me, if you don’t get a satisfactory response

`r vspace("50px")`

## Questions about your programme / visa arrangements / exam entries / etc.

- Jinghao ([jinghao.xue@ucl.ac.uk](mailto: jinghao.xue@ucl.ac.uk)) or Agnes ([a.somogyi@ucl.ac.uk](mailto: a.somogyi@ucl.ac.uk)) 
